// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var Axios = require("axios");

function get(config) {
  console.log("start get function");
  console.log("config: ", config);
  return Axios(config);
}

exports.get = get;
/* axios Not a pure module */
