// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Http = require("./utils/Http.bs.js");

var uri = "https://api.github.com/users";

async function postBanana(param) {
  var res = Http.get({
        url: uri,
        headers: [[
            "Content-type",
            "application/json"
          ]]
      });
  var success = await res;
  if (success.TAG === /* Ok */0) {
    console.log("Success: ", success._0);
    return ;
  }
  console.log("switch Error: ", success._0);
}

var result = postBanana(undefined);

console.log("result: ", result);

exports.uri = uri;
exports.postBanana = postBanana;
exports.result = result;
/* result Not a pure module */
